CC=gcc
CFLAGS=-std=c99 -pedantic -pedantic-errors -Werror -Wall -Wextra

all: my_args my_range my_tree

my_args: my_args.c
my_range: my_range.c
my_tree: my_tree.c

clean:
	rm -f my_args
	rm -f my_range
	rm -f my_tree